### ISSUE TITLE
Storage config to DB selection

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#1169]
In general, storage abstraction allows for organizations to run a Nuts node with their preferred storage. To enable this a config setup is needed that is somehow used when instantiating a kind of storage in code. We identified different types of storage:

- Volatile: storage that may be removed and nothing really bad happens. eg: db connection state
- Bulk: storage that is needed by a node but can be built from network state. You don't want to rebuild it since it will cost a lot of time. eg: DAG, public payloads
- Critical: storage that can't be rebuild and needs to be backed-up, eg: private payloads, issued credentials
- Index: storage that allows for searching, can be rebuild from Bulk. Data in this type of storage will typically reside in-memory (for faster searching). You don't want to rebuild it since it will cost a lot of time. eg: VCR, VDR.

The configuration file should be simple to use, eg: "this is my redis storage". It should feature sane defaults but still allow for a particular setup.

```yaml
storage:
  adapters:
    volatile:
      type: bbolt
      config:
        datadir: data
    default:
      type: redis
      config:
        key: value
        key2: value
    private:
      type: redis
      config:
        key: value
        key2: value
    index:
      type: elastic
      config:
        key: value
        key2: value

```

`default` will be used for the DAG (and payloads and private if not configured separately). No index means a default leia on bbolt store in the same as `volatile`. `volatile` by default will be bbolt on disk.

Engines in nuts-core know which type of storage they need, they can request it from the storage engine:

```
storage.GetVolatile(...)
storage.GetDefault(...)
// etc
```

So we have different storage `classes`. For each class multiple instances (identified by `name`) can exist. It's up to the adapter to translate the name to something else (buckets, tables, logical DBs, etc).

**Comment by woutslakhorst** [comment]
For a future version:

The current indexing lib (go-leia) is hooked to bbolt on disk which doesn't allow for multiple readers. It would be best to create an interface for searching and provide multiple implementations. Some research is needed to see if goleia can be transformed so it uses a generic query language compatible with other indexing capable DBs

**Comment by reinkrul** [comment]
The proposed solution mixes concerns: storage class (volatile/default(?)/private) with type (index). I think the application should request a specific type of storage (KV/index/etc) through APIs (e.g. `GetKVStore`/`GetIndexStore`). The storage engine can then be configured with backend data storage (bbolt/redis/etc), which map to a storage class. As such, I don't think we need to introduce the concept of "storage class" (volatile/default/bulk) in the application and just be a documentation concern (since it all depends what kind of backend data storage you use).

I'd say by default everything goes into BBolt (KV) and leia (index), which can then be overridden in storage config:
```
storage:
  stores:
    network/private-txs:
      type: redis
      config:
        key: value
        key2: value
    vdr/did-documents:
      type: elastic
      config:
        key: value
        key2: value
    vcr/vcs:
      type: elastic
      config:
        key: value
        key2: value
```

**Comment by woutslakhorst** [comment]
The multiple reader problem arises when updating your cloud node, it usually spins up the new one first before closing the old one. This default behaviour is blocked by our implementation.

Letting the user configure each DB is quite a nuisance, since they'll have to configure 8 different instances instead of 2. From a user perspective the easiest is to define where their bulk data lives and where their to-be-backed-up storage lives.

**Comment by reinkrul** [comment]
Another suggestions:

 When the application requests a store, it provides the expected storage class:
 GetKVStore(name, storageClass)
 Storage class is either volatile (can be lost without major consequences) or persistent (must be retained, serious data loss)
 These are the expected stores and classes:
 - network DAG txs: persisted
 - network payloads: persisted
 - network private payload jobs: persisted
 - network outbound connectors: volatile
 - VCR/VDR indexes: persisted
 - VCR issued VCs: persisted
 Each supported storage type has a default associated storage class: redis = persisted, bbolt = volatile
 In non-strict mode, a volatile storage can be used if so persistent storage is found

**Comment by woutslakhorst** [comment]
What we could do for now is to use a single DB and backup everything. Way to much will be stored, but in the beginning this is peanuts. Some hard coded DBs will still exist:

- connections: hardcoded bbolt
- DAG (XOR, IBLT, Clocks): configured DB
- Payloads (public, private and jobs): configured DB
- VDR: hardcoded bbolt for index, reuse of payloads
- VCR: same (plus issuer and verifier)

**Comment by reinkrul** [comment]
VCR issued VCs (and revocations) is just an index as well, just like VCR's verifier store and VDR's DID document store: they but then from private payloads, rather than the public ones.

**Comment by woutslakhorst** [comment]
There's not a really big reason to separate the payloads. It might be useful in the future, but that's an easy migration.

**Comment by reinkrul** [comment]
Simplified config example:

```
storage:
  databases:
    # Redis is not enabled by default, configuring it makes a persistent store available.
    # All persistent storage will then be Redis.
    redis:
      key1: value 1
      key2: value 2
    # BBolt is enabled (and used) by default, but this allows to configure additional options.
    bbolt:
```

To support backing up specific BBolt stores (that require backing up), we could specify this in the BBolt config;

```
storage:
    bbolt:
      backup:
        interval: 1m
        path: /backup/mount/path
        stores:
          - network/store1
          - vcr/other-store
```
