### ISSUE TITLE
VCR: ResolveVC shouldn't check trust status

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#1221]
According to the OpenAPI description, it shouldn't check the trust status. But it does it nonetheless, and there is no way to override this behaviour (e.g. with an `allowUntrusted` parameter).

```
    get:
      summary: "Resolves a verifiable credential"
      description: >
        Returns the resolved credential, whether its revocation/trust state.
```

Output:

```
{
    "detail": "credential issuer is untrusted",
    "status": 500,
    "title": "ResolveVC failed"
}
```

If an application wants to assert the VC is valid it should use `verifyVC` instead.
