### ISSUE TITLE
gRPC cosmetic improvement

### ISSUE THREAD

**Issue by olafz** [nuts-foundation/nuts-node#1406]
Currently, the gRPC client calls from the Nuts-node to other nodes are performed with a `grpc-go/x.y.z` User-Agent. It would be a cosmetic improvement to show something like `nuts-node/4.2.2` as User-Agent.

Abstract from a log line currently in our proxy:

```
TLSv1.3 hostname.tld:5555 "POST /v2.Protocol/Stream HTTP/2.0" 200 0 0.007 "-" "grpc-go/1.46.2"
```

PS: This might be the case in other situations as well

**Comment by woutslakhorst** [comment]
We could inherit it from the build info that is injected at compile time:

```
status:
    git_commit: 22df84739e2ef8c3e6ddee28e90260ed3a9dc243
    os_arch: linux/amd64
    software_version: v4.2.0
    uptime: 47h18m38s
```

Only the name should be hardcoded: "Nuts Reference Implementation" and then adjust for User-Agent requirements
