### ISSUE TITLE
`connected_peers` on incoming connections behind proxy show 127.0.0.1 as IP address

### ISSUE THREAD

**Issue by olafz** [nuts-foundation/nuts-node#1500]
Our nuts node runs behind an incoming reverse proxy (Nginx) that has several headers set to indicate the origin IP:

```
(...)
grpc_set_header X-Real-IP $remote_addr;
grpc_set_header X-Forwarded-For $remote_addr;
(...)
```

This is according to the documentation at https://nuts-node.readthedocs.io/en/latest/pages/deployment/recommended-deployment.html#reverse-proxy.

In some situations this works as expected. For example, in the logging the external IP is usually shown:
```
time="2022-10-01T14:27:40Z" level=info msg="HTTP request" method=POST module=http-server remote_ip=144.2.168.5 status=200 uri=/n2n/auth/v1/accesstoken
```

However, in other situations, it is not. For example a call to `nuts status` shows all inbound gRPC connections with IP address `127.0.0.1`:

```
network:
    connections:
        connected_peers:
            - id: 8435c274-76e3-4412-bd4e-798e62708365
              address: 127.0.0.1:40302
              nodedid: did:nuts:BiA7Z9KeeELMCEcrgWm7WsUybJazLBuVjZru467mLSnd
              acceptunauthenticated: false
            - id: daf97159-6595-4f82-a107-3101d27cfc4b
              address: 127.0.0.1:40308
              nodedid: did:nuts:8WaMU8FQGeyNr2xVGAxuNwjmgajYLyhvBSRfC3nZ2PNo
              acceptunauthenticated: false
            - id: 1e9b644b-5af8-40a0-bd3c-f522f60fc9d5
              address: 127.0.0.1:40318
              nodedid: did:nuts:HVJBgpB9s9P5zaYSQPaadxgDf4qc86uWAGmvepBafXTs
              acceptunauthenticated: false
```
