### ISSUE TITLE
VCR: SearchVCs filters on context URI

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#1574]
While testing release candidates v4.3.0 and v5.0.0, which should be able to exchange `NutsAuthorizationCredential@v1` and `NutsAuthorizationCredential@v2` with each other, I noticed a search query specifying the Nuts v1 JSON-LD context not returning `NutsAuthorizationCredential@v2` credentials, and vice versa. This is bad for 2 reasons:

1. Since the JSON-LD context URI only serves to resolve the actual context, filtering it makes no sense. Instead of the context URI, the context (in expanded form) could've been there, which would also have been valid JSON-LD.
2. Applications now need to perform 2 searches when searching NutsAuthorizationCredentials (regardless of context version), first with the v1 context and then with the v2 context.

Should also be backported to v4.3.0 for forward compatibility with v2 credentials.

**Comment by reinkrul** [comment]
`go-leia` is also configured (hardcoded) to index v1 credentials, this is missing v2?

`vcr/assets/assets/default.index.yaml:22`:

```
  - name: index_auth_subject
    parts:
      - iriPath: ["https://www.w3.org/2018/credentials#credentialSubject"]
      - iriPath: ["https://www.w3.org/2018/credentials#credentialSubject", "https://nuts.nl/credentials/v1#subject"]
```
