### ISSUE TITLE
Investigate broken sync on master

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#2405]
v5.4.1 syncs perfectly but my 2nd development node stops at 523 TXs. (Uses redis)

**Comment by woutslakhorst** [comment]
3 fresh syncs on master, all resulted in the following state:

```
    state:
        dag_lc_high: 451
        dag_xor: 183fd2bfb130d879fed69b3bf3d5a54203e76f3773bdb089cc71676a3d5f4607
        failed_events: 1
        stored_database_size_bytes: 1900544
        transaction_count: 555
```

And this error message:

```
ERRO[0071] Error handling message                        error="unable to add received transaction to DAG (tx=32204ec564a7fe2c0f8ae8814021bb8cc91d383149c63ca67ff1ccb9fabc8f27): transaction verification failed (tx=32204ec564a7fe2c0f8ae8814021bb8cc91d383149c63ca67ff1ccb9fabc8f27): unable to verify transaction signature, can't resolve key by TX ref (kid=did:nuts:4U3Coi5kVrhudjE3qtEY7hNsTCYK1LcFEG4XMEfkqSdp#M4A78t4uELjUOcqnCh_DzsCxn3mWkDMvtxJqxUFS8ws, tx=32204ec564a7fe2c0f8ae8814021bb8cc91d383149c63ca67ff1ccb9fabc8f27): unable to find the DID document" messageType="*v2.Envelope_TransactionList" module=Network peerAddr="nuts-development.reinkrul.nl:8443" peerAuthenticated=false peerDID= peerID=70f9fae2-1a18-4292-9e3a-e0dda52d0713
```
