### ISSUE TITLE
Default url + http config is not developer friendly

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#2857]
A minimum config for running the nuts-node will require:

```
url:https://nuts.local:9443
auth.v2apienabled: true
http:
  alt:
    iam:
      tls: server
      address: :9443
tls:
  truststorefile: /opt/nuts/truststore.pem
  certfile: /opt/nuts/certificate-and-key.pem
  certkeyfile: /opt/nuts/certificate-and-key.pem
```

or variations due to did:web
