### ISSUE TITLE
Simplify HTTP configuration

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#2860]
The current HTTP configuration is too complex:
- It allows the Nuts node to terminate TLS, but this doesn't work in practice. You need to serve 2 certificates (for public and n2n), but only 1 can be configured
- You need additional configuration to have a feasible setup, even in development:
   - For resolving your own `did:web` DIDs, you need to terminate TLS. But doing so requires a TLS certificate, HTTPS configuration and alternative bindings
   - But to avoid making the status, health, and internal API endpoints unavailable, you need additional bindings
- Default configuration is unsecure: public endpoints are on the same port as the internal API, without authentication

Suggestion:
- Introduce 2 HTTP interfaces which replace the current HTTP bind configuration:
  - `0.0.0.0:8080` for external endpoints (`/public`, `/iam`, `/n2n`, `/.well-known`)
  - `localhost:8081` for admin endpoints (`/internal`, `/status`, `/health`)
- No server-side HTTPS support: in deployed environments, TLS will be terminated in a reverse proxy/ingress
- API authentication only applicable to `/internal` endpoints; it does not make sense for the others.
- Introduce a new `dev` Docker image for easier development:
  - embeds `ngrok` to "deploy" a HTTPS proxy for the Nuts node, which is required to resolve the node's `did:web` DIDs
  - binds the admin interface to `0.0.0.0:8081` to make it accessible from outside the Docker container
- Keep TLS support for gRPC unchanged (will be removed in future anyway)

While the default configuration works in simple deployments, the most extensive configuration (will all options utilized) could look as follows:

```yaml
http:
  log: request-reply                    # HTTP request/reply logging configuration
  external:                             # Configuration for public-facing endpoints
    address: 0.0.0.0:80                 # Listen on all interfaces on port 80
  admin:                                # Configuration for administrative endpoints
    address: 0.0.0.0:8080               # Listen on all interfaces on port 8080
    api_auth:                           # Configuration API authentication on /internal
      type: token_v2
      authorizedkeyspath: /etc/authz
      audience: api.example.com
```

This drops the following features:
- CORS headers (used for IRMA deployments), these can be set by the reverse proxy if required.
- TLS termination (HTTPS) on the Nuts node, this is always done by a reverse proxy
- Mapping endpoints to specific ports (it's still possible to specify a different port for a set of endpoints)
