### ISSUE TITLE
VDR API for creating a new Nuts DID returns result conflicting with the spec

### ISSUE THREAD

**Issue by jelmerterwal** [nuts-foundation/nuts-node#365]
When I run a POST call to generate a customer DID (https://nuts-node.readthedocs.io/en/latest/pages/getting-started/4-connecting-crm.html#create-and-store-a-customer-did) the returned data provides a `string` in the `controller` field whereas the specification tells me it is of type `[string]`. This makes generated Open API clients fail on these requests.

A bit of history; client generation didn't work when `OneOf` was being used earlier (for some languages at least).

**Comment by woutslakhorst** [comment]
According to the DID spec some fields may be either a `[string]` or `string`. This conflicts with OAS code generation. Using `oneOf`/`anyOf` in OAS is not supported by all code generators.

**Comment by woutslakhorst** [comment]
current OAS says:

```
controller:
          description: List of DIDs that have control over the DID document
          type: array
          items:
            type: string
```
