### ISSUE TITLE
Inconsistency in generated API

### ISSUE THREAD

**Issue by jelmerterwal** [nuts-foundation/nuts-node#858]
`context` vs `@context` in diddocument messes up api generated code.

https://github.com/nuts-foundation/go-did/blame/master/did/document.go#L20
https://github.com/nuts-foundation/nuts-node/blob/master/docs/_static/vdr/v1.yaml#L247

Also `capabilityInvocation` is not part of the open api specification.

Required changes so far;
```
        capabilityInvocation:
           type: array
           items:
             type: string
        keyAgreement:
          type: array
          items:
            type: string
        '@context':
#          description: List of URIs
#          type: array
#          items:
          type: string
```
