### ISSUE TITLE
Add JSON-LD @context configuration

### ISSUE THREAD

**Issue by stevenvegt** [nuts-foundation/nuts-node#943]
Adds config options:

```yaml
vcr:
  jsonldcontexts:
    remoteallowlist:
      - "http://schema.org"
      - "http://nuts.com/contexts/v1.json"
    localmapping:
    - url: "http://kikv.com"
      path: kikv.json
    - url: "http://foo.bar.com/context.json"
      path: foo-context.json
```
