### ISSUE TITLE
Some dates in vcr/v2.yaml have a format: date-time, most have not

### ISSUE THREAD

**Issue by rolandgroen** [nuts-foundation/nuts-node#964]
The docs/_static/vcr/v2.yaml file has most date values represented as strings without format, for example:

```
components:
  schemas:
    IssueVCRequest:
....
        expirationDate:
          description: rfc3339 time string until when the credential is valid.
          type: string
          example: "2012-01-02T12:00:00Z"
```

But  for the following  3 fields, the format is set to date-time:

* CreateVPRequest.expires
* VPVerificationRequest.validAt
* VerifiablePresentation.proof(EmbeddedProof).created

Example:

```
        expires:
          type: string
          description: Date and time at which proof will expire. If omitted, the proof does not have an end date.
          format: date-time
          example: '2021-12-20T09:00:00Z'
```

No other date fields in the projects' openapi definitions have the `format: date-time` set. 

The 3 fields seem to have the format set to rfc3339, and the openapi definition of the date-time matches the rfc3339 format.

This causes some issues with the generated clients, as they tend to treat fields with the `format: date-time` as date fields and the others as plain strings.

For consistency, it would make sense to either  set the date format for all the date fields, or for none.
